######################################################################
# Automatically generated by qmake (2.01a) sam. 11. oct. 21:00:52 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += fen.h
FORMS += 3T.ui
SOURCES += fen.cpp main.cpp
RESOURCES += images.qrc
